scheme: Pisces

darkmode: true

preconnect: true

post_meta:
  updated_at: false

menu:
  home: / || fa fa-home
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  概念图: https://cmap.huhao.dev || fa fa-lightbulb
  about: /about/ || fa fa-user
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/safari-pinned-tab.svg
  android_manifest: /images/site.webmanifest
  ms_browserconfig: /images/browserconfig.xml

toc:
  expand_all: true

avatar:
  url: https://huhao-dev.oss-cn-beijing.aliyuncs.com/2020-01-23-avatar.jpg
  rounded: false

footer:
  since: 2019

social:
  GitHub: https://github.com/howiehu || fab fa-github
  Weibo: https://weibo.com/howiehu || fab fa-weibo
  Zhihu: https://www.zhihu.com/people/howiehu || fab fa-zhihu
  RSS: /atom.xml || fa fa-rss

social_icons:
  icons_only: true
  transition: true

creative_commons:
  license: by-nc-nd
  sidebar: true
  post: true
  language: deed.zh

github_banner:
  enable: true
  permalink: https://github.com/howiehu
  title: Follow me on GitHub

# Reward (Donate)
# Front-matter variable (unsupport animation).
reward_settings:
  # If true, reward will be displayed in every article by default.
  enable: true

reward:
  wechatpay: /images/wechatpay.jpg
  alipay: /images/alipay.jpg

# Utterances
# For more information: https://utteranc.es
utterances:
  enable: true
  repo: howiehu/huhao.dev
  # Available values: pathname | url | title | og:title
  issue_term: pathname
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: preferred-color-scheme

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

seo: true

index_with_subtitle: true

bing_site_verification: 0F08F252C8D1F3EDE6EA6BFDFCDCACFB

baidu_site_verification: 17XyprouqJ
